#pragma once

#include <QObject>

enum PatternType {
	ELLIPSE_PATTERN = 0,
	POLYGON_PATTERN = 1,
	GAUSSIAN_PATTERN = 2,
};


enum AntialisingType {
	ANTIALISING = 0,
	NOANTIALISING = 1,
};


enum BackgroundColor {
	WHITE_BACKGROUND = 0,
	BLACK_BACKGROUND = 1,
};


enum TransformType {
	TRANSLATION_DEFORMATION = 0,
	ELONGATION_DEFORMATION = 1,
	SINUSOIDAL_DEFORMATION = 2,
	GAUSSIAN_DEFORMATION = 3,
	PLC_BAND_DEFORMATION = 4,
	ROTATION_DEFORMATION = 5,
	TWO_DIMENSIONAL_SINUSOIDAL_DEFORMATION = 6,
	TWO_DIMENSIONAL_GAUSSIAN_DEFORMATION = 7,
};


enum AssessType {
	ASSESS_COVERAGE = 0,
	ASSESS_AUTOCORRELATION = 1,
	ASSESS_BIAS = 2,
	ASSESS_NOISE = 3,
};


enum InterpolationAlgorithm {
	KEYS_INTERPOLATION = 0 ,
	CUBIC_BSPLINE_INTERPOLATION = 1,
	QUINTIC_BSPLINE_INTERPOLATION = 2,
	SEPTIC_BSPLINE_INTERPOLATION = 3,
};